-- Import masivo de jugadores desde Excel (planilla todo maestros .xlsx)
-- Incluye posicion principal y secundaria
BEGIN;

ALTER TABLE jugadores ADD COLUMN IF NOT EXISTS categoria text;
ALTER TABLE jugadores ADD COLUMN IF NOT EXISTS numero int;
ALTER TABLE jugadores ADD COLUMN IF NOT EXISTS posicion text;
ALTER TABLE jugadores ADD COLUMN IF NOT EXISTS posicion_2 text;

DELETE FROM jugadores WHERE categoria IN ('Junior Fútbol','Senior Fútbol','Super Senior Futbolito','Super Senior Fútbol') OR categoria IS NULL;

INSERT INTO jugadores (categoria, nombre, apodo, apellido, fecha_nacimiento, numero, posicion, posicion_2) VALUES
  ('Super Senior Fútbol', 'Javier', 'Tira', 'Acevedo Vogel', '1980-11-28', 16, 'DEF', NULL),
  ('Super Senior Futbolito', 'Javier', 'Tira', 'Acevedo Vogel', '1980-11-28', 16, 'DEF', NULL),
  ('Super Senior Fútbol', 'José Antonio', 'Pepe', 'Achondo Villaseca', '1980-08-17', 8, 'MED', NULL),
  ('Super Senior Futbolito', 'José Antonio', 'Pepe', 'Achondo Villaseca', '1980-08-17', 8, 'MED', NULL),
  ('Junior Fútbol', 'Diego', NULL, 'Allende Martínez', '2004-09-20', 26, NULL, NULL),
  ('Junior Fútbol', 'Santiago', NULL, 'Allende Martínez', '2002-01-09', 17, NULL, NULL),
  ('Super Senior Fútbol', 'Francisco', 'Negro', 'Amenábar Riumalló', '1981-05-15', 3, 'MED', 'DEF'),
  ('Super Senior Futbolito', 'Francisco', 'Negro', 'Amenábar Riumalló', '1981-05-15', 5, 'MED', 'DEF'),
  ('Junior Fútbol', 'Juan', NULL, 'Arteaga Mackenna', '2006-11-13', 28, NULL, NULL),
  ('Super Senior Fútbol', 'José Miguel', NULL, 'Astete Stewart', '1982-10-17', 35, 'DEF', NULL),
  ('Super Senior Futbolito', 'José Miguel', NULL, 'Astete Stewart', '1982-10-17', 35, 'DEF', NULL),
  ('Junior Fútbol', 'Diego', NULL, 'Azócar Simian', '2006-11-07', 14, NULL, NULL),
  ('Super Senior Fútbol', 'Gabriel', NULL, 'Bagadnani -', '1976-01-02', 40, NULL, NULL),
  ('Super Senior Fútbol', 'Santiago', NULL, 'Barros Prieto', '1980-07-14', 31, NULL, NULL),
  ('Junior Fútbol', 'Jorge', NULL, 'Benavente Cruz', '2004-06-18', 33, NULL, NULL),
  ('Senior Fútbol', 'Sebastián', 'Chico', 'Benavente Larrain', '1980-09-12', 6, 'DEF', NULL),
  ('Super Senior Fútbol', 'Sebastián', 'Chico', 'Benavente Larrain', '1980-09-12', 6, 'DEF', NULL),
  ('Super Senior Futbolito', 'Sebastián', 'Chico', 'Benavente Larrain', '1980-09-12', 6, 'DEF', NULL),
  ('Senior Fútbol', 'Diego', NULL, 'Bunster Echenique', '1983-11-07', 1, 'POR', NULL),
  ('Super Senior Fútbol', 'Diego', NULL, 'Bunster Echenique', '1983-11-07', 1, 'POR', NULL),
  ('Super Senior Futbolito', 'Hernán', NULL, 'Bustamante Martin', '1980-05-20', 11, 'MED', NULL),
  ('Super Senior Fútbol', 'Sebastián', 'Murcy', 'Calderón Lathrop', '1982-11-03', 21, 'DEF', 'MED'),
  ('Super Senior Fútbol', 'Matías', 'Pelao', 'Calvo Aldunate', '1980-12-30', 15, 'DEF', NULL),
  ('Super Senior Futbolito', 'Matías', 'Pelao', 'Calvo Aldunate', '1980-12-30', 15, 'DEF', NULL),
  ('Junior Fútbol', 'Stéfano', NULL, 'Casella Cabrera', '2002-03-13', 10, NULL, NULL),
  ('Junior Fútbol', 'Cecil', NULL, 'Chellew Galilea', '1992-10-13', 20, NULL, NULL),
  ('Junior Fútbol', 'Diego', NULL, 'Chicoma Fuentealba', '2000-10-04', 6, NULL, NULL),
  ('Senior Fútbol', 'Tomás', NULL, 'Collao Varela', '1996-10-16', 71, NULL, NULL),
  ('Junior Fútbol', 'Agustín', NULL, 'Concha Prieto', '1993-02-12', 10, NULL, NULL),
  ('Senior Fútbol', 'Javier', NULL, 'Concha Prieto', '1990-11-25', 16, NULL, NULL),
  ('Junior Fútbol', 'Cristián', NULL, 'Concha Rojas', '2007-12-29', 3, NULL, NULL),
  ('Junior Fútbol', 'Domingo', NULL, 'Correa Ariztía', '2002-05-02', 8, NULL, NULL),
  ('Super Senior Futbolito', 'Héctor', 'Payo', 'Correa Pereira', '1979-11-28', 34, 'MED', NULL),
  ('Super Senior Futbolito', 'Benjamín', 'Chato', 'Costa Navarro', '1979-11-30', 22, 'DEF', NULL),
  ('Super Senior Futbolito', 'Tomás', 'Tomy', 'Covarrubias Covarrubias', '1980-05-20', 17, 'MED', NULL),
  ('Senior Fútbol', 'Felipe', 'Turbo', 'Cruz Tuñón', '1980-07-19', 77, 'DEL', NULL),
  ('Super Senior Fútbol', 'Felipe', 'Turbo', 'Cruz Tuñón', '1980-07-19', 7, 'DEL', NULL),
  ('Senior Fútbol', 'Sebastián', NULL, 'Cuevas Braun', '1991-08-07', 5, NULL, NULL),
  ('Junior Fútbol', 'Martín', NULL, 'De la Carrera Vizcaya', '2000-02-10', 35, NULL, NULL),
  ('Junior Fútbol', 'Tomás', NULL, 'De la Carrera Vizcaya', '2006-04-24', 21, NULL, NULL),
  ('Junior Fútbol', 'José Pedro', NULL, 'Del Rio Velasco', NULL, 16, NULL, NULL),
  ('Super Senior Futbolito', 'Juan Carlos', 'Chino', 'Díaz Echeverría', '1980-11-12', 12, 'DEL', 'POR'),
  ('Senior Fútbol', 'Matías', NULL, 'Díaz de Valdés Abell', '1992-01-26', 11, NULL, NULL),
  ('Super Senior Futbolito', 'Michel', NULL, 'Dibán Giacomann', '1980-07-10', 21, 'DEF', NULL),
  ('Super Senior Fútbol', 'Francisco', 'Chumi', 'Domínguez Larrain', '1980-07-18', 23, 'DEF', NULL),
  ('Super Senior Futbolito', 'Francisco', 'Chumi', 'Domínguez Larrain', '1980-07-18', 23, 'DEF', NULL),
  ('Senior Fútbol', 'Nicolás', NULL, 'Domínguez Navarro', '1980-09-13', 30, 'DEF', 'DEL'),
  ('Super Senior Futbolito', 'Nicolás', NULL, 'Domínguez Navarro', '1980-09-13', 30, 'DEF', 'DEL'),
  ('Super Senior Fútbol', 'José Miguel', 'Huaso', 'Echenique Barros', '1980-01-30', 60, 'DEF', 'MED'),
  ('Super Senior Futbolito', 'José Miguel', 'Huaso', 'Echenique Barros', '1980-01-30', 60, 'DEF', 'MED'),
  ('Junior Fútbol', 'Ignacio', NULL, 'Errázuriz Arrau', '2000-04-12', 40, NULL, NULL),
  ('Senior Fútbol', 'Bastián', NULL, 'Fuentes Díaz', '1995-04-04', 17, NULL, NULL),
  ('Senior Fútbol', 'Nicolás', NULL, 'Gallego Pereira', '1982-02-12', 13, 'DEF', NULL),
  ('Super Senior Fútbol', 'Nicolás', NULL, 'Gallego Pereira', '1982-02-12', 13, 'DEF', NULL),
  ('Super Senior Fútbol', 'Cristián', NULL, 'Gana Arteaga', '1983-01-18', 26, 'MED', NULL),
  ('Super Senior Futbolito', 'Cristián', NULL, 'Gana Arteaga', '1983-01-18', 26, 'MED', NULL),
  ('Super Senior Fútbol', 'Luis Alberto', NULL, 'Gana Arteaga', '1979-12-06', 4, 'MED', NULL),
  ('Super Senior Futbolito', 'Luis Alberto', NULL, 'Gana Arteaga', '1979-12-06', 4, 'MED', NULL),
  ('Senior Fútbol', 'Cristián', NULL, 'Garcés Contador', '1980-12-19', 8, 'DEF', 'MED'),
  ('Super Senior Fútbol', 'Cristián', NULL, 'Garcés Contador', '1980-12-19', 17, 'DEF', 'MED'),
  ('Super Senior Fútbol', 'Rodrigo', NULL, 'Garcés Ossa', '1980-02-26', 9, 'DEL', NULL),
  ('Super Senior Futbolito', 'Rodrigo', NULL, 'Garcés Ossa', '1980-02-26', 10, 'DEL', NULL),
  ('Super Senior Futbolito', 'Manuel', NULL, 'García de los Rios Concha', '1980-08-07', 18, 'DEL', NULL),
  ('Junior Fútbol', 'Benjamín', NULL, 'Gillet Del Solar', '2007-12-24', 19, NULL, NULL),
  ('Senior Fútbol', 'Antonio', NULL, 'Gonel Garcés', '1993-12-20', 19, NULL, NULL),
  ('Super Senior Fútbol', 'Álvaro Nicolás', NULL, 'González Rojas', '1982-02-24', 5, NULL, NULL),
  ('Super Senior Fútbol', 'Sebastián', 'Chama', 'González Valdés', '1978-12-14', 32, 'DEL', 'MED'),
  ('Super Senior Futbolito', 'Sebastián', 'Chama', 'González Valdés', '1978-12-14', 32, 'DEL', 'MED'),
  ('Super Senior Futbolito', 'Rodrigo', NULL, 'Guzmán Mingo', '1980-09-01', 29, 'POR', NULL),
  ('Senior Fútbol', 'Mauricio', NULL, 'Heresi Idieder', '1992-10-24', 24, NULL, NULL),
  ('Super Senior Fútbol', 'Felipe', 'Huicho', 'Huidobro García', '1980-03-17', 25, 'DEF', NULL),
  ('Super Senior Fútbol', 'Arturo', NULL, 'Labbé Moreno', '1980-08-20', 2, 'DEF', NULL),
  ('Super Senior Futbolito', 'Arturo', NULL, 'Labbé Moreno', '1980-08-20', 2, 'DEF', NULL),
  ('Super Senior Futbolito', 'Raúl', NULL, 'Lagos Izquierdo', '1984-02-19', 20, 'MED', NULL),
  ('Senior Fútbol', 'Camilo', NULL, 'Le Feuvre Rodríguez', '1989-07-03', 14, NULL, NULL),
  ('Junior Fútbol', 'Raimundo', NULL, 'Lyon Montes', '2002-09-06', 4, NULL, NULL),
  ('Junior Fútbol', 'Rodrigo', NULL, 'Lyon Montes', '1997-04-01', 15, NULL, NULL),
  ('Senior Fútbol', 'Rodrigo', NULL, 'Lyon Montes', '1997-04-01', 15, NULL, NULL),
  ('Junior Fútbol', 'Jorge', NULL, 'Mackenna Cooper', '1991-01-02', 99, NULL, NULL),
  ('Senior Fútbol', 'Jorge', NULL, 'Mackenna Cooper', '1991-01-02', 99, 'DEL', NULL),
  ('Junior Fútbol', 'Pablo', NULL, 'Mackenna Cooper', '1992-09-29', 7, NULL, NULL),
  ('Senior Fútbol', 'Pablo', NULL, 'Mackenna Cooper', '1992-09-29', 7, 'DEL', NULL),
  ('Senior Fútbol', 'Rodrigo', NULL, 'Mackenna Cooper', '1980-07-02', 25, 'MED', 'DEL'),
  ('Super Senior Fútbol', 'Rodrigo', 'Tito', 'Mackenna Cooper', '1980-07-02', 10, 'MED', 'DEL'),
  ('Super Senior Futbolito', 'Rodrigo', 'Tito', 'Mackenna Cooper', '1980-07-02', 25, 'MED', 'DEL'),
  ('Super Senior Futbolito', 'Francisco', NULL, 'Márquez -', '1983-06-08', 19, NULL, NULL),
  ('Super Senior Fútbol', 'Lucas', NULL, 'Mira Hurtado', '1988-07-22', 33, 'DEL', NULL),
  ('Super Senior Futbolito', 'Raúl', NULL, 'Molina Barros', '1981-09-14', 1, 'POR', NULL),
  ('Senior Fútbol', 'Luis', NULL, 'Moller Verderau', '1991-03-07', 20, 'MED', NULL),
  ('Junior Fútbol', 'Vicente', NULL, 'Montero Echeverría', '2001-04-03', 24, NULL, NULL),
  ('Junior Fútbol', 'Francisco', NULL, 'Montero Silva', '2001-11-15', 2, NULL, NULL),
  ('Junior Fútbol', 'José Tomás', NULL, 'Muñoz Wilson', '1994-06-07', 22, NULL, NULL),
  ('Senior Fútbol', 'José Tomás', NULL, 'Muñoz Wilson', '1994-06-07', 22, NULL, NULL),
  ('Senior Fútbol', 'Tomás', NULL, 'Naudon Dell´Oro', '1991-07-24', 32, NULL, NULL),
  ('Senior Fútbol', 'Agustín', 'Aquino', 'Navarro Armanet', '1994-06-07', 18, NULL, NULL),
  ('Super Senior Fútbol', 'Mauricio', NULL, 'Navarro Armanet', '1983-05-01', 20, NULL, NULL),
  ('Super Senior Fútbol', 'Luis Felipe', 'Luisfe', 'Navarro Soffia', '1977-10-24', 47, 'DEF', NULL),
  ('Junior Fútbol', 'Felipe', NULL, 'Ochagavía Eguiguren', '1993-09-16', 1, NULL, NULL),
  ('Senior Fútbol', 'Felipe', NULL, 'Ochagavía Eguiguren', '1993-09-16', 28, NULL, NULL),
  ('Senior Fútbol', 'Vicente', NULL, 'Ossandón Del Fávero', '1993-08-19', 23, NULL, NULL),
  ('Super Senior Futbolito', 'Andrés', NULL, 'Parker Parada', '1983-03-17', 28, NULL, NULL),
  ('Super Senior Fútbol', 'Andrés', 'Pinturro', 'Pinto Chicharro', '1979-11-01', 14, 'DEF', 'MED'),
  ('Super Senior Futbolito', 'Andrés', 'Pinturro', 'Pinto Chicharro', '1979-11-01', 14, 'DEF', 'MED'),
  ('Junior Fútbol', 'Francisco', NULL, 'Pirazzoli Luengo', '1998-11-03', 32, NULL, NULL),
  ('Junior Fútbol', 'Juan Pablo', NULL, 'Porter Oyarzún', '2000-05-02', 9, NULL, NULL),
  ('Junior Fútbol', 'José Miguel', NULL, 'Prieto Tchobanian', '2008-03-05', 30, NULL, NULL),
  ('Junior Fútbol', 'Justo', NULL, 'Prieto', NULL, 12, NULL, NULL),
  ('Super Senior Futbolito', 'Felipe', 'Roto', 'Reyes Polanco', '1983-11-02', 13, 'MED', 'DEL'),
  ('Junior Fútbol', 'Felipe', NULL, 'Rivas Correa', '2001-03-07', 80, NULL, NULL),
  ('Senior Fútbol', 'Matías', NULL, 'Rodríguez Perez', '1980-10-12', 38, NULL, NULL),
  ('Super Senior Fútbol', 'Matías', NULL, 'Rodríguez Perez', '1980-10-12', 38, NULL, NULL),
  ('Junior Fútbol', 'Francisco', NULL, 'Sande Guglielmetti', '1994-06-18', 18, NULL, NULL),
  ('Junior Fútbol', 'Juan Pablo', NULL, 'Sande Guglielmetti', '2002-05-13', 11, NULL, NULL),
  ('Junior Fútbol', 'Luis Felipe', NULL, 'Sande', NULL, 23, NULL, NULL),
  ('Junior Fútbol', 'Alfonso', NULL, 'Sanhueza Pinochet', '2006-03-03', 25, NULL, NULL),
  ('Senior Fútbol', 'Clemente', NULL, 'Sepúlveda Vial', '1995-01-19', 45, NULL, NULL),
  ('Junior Fútbol', 'David', NULL, 'Silva Millares', '2005-09-10', 29, NULL, NULL),
  ('Senior Fútbol', 'Matías', NULL, 'Suárez -', '1979-06-27', 27, 'DEL', NULL),
  ('Super Senior Fútbol', 'Matías', NULL, 'Suárez -', '1979-06-27', 27, 'DEL', NULL),
  ('Senior Fútbol', 'Nicolás', NULL, 'Tagle Carvallo', '1992-05-14', 33, NULL, NULL),
  ('Super Senior Fútbol', 'Carlos', 'Caco', 'Ubilla Lorca', '1982-07-15', 22, 'DEF', NULL),
  ('Super Senior Futbolito', 'Patricio', 'Pato', 'Valdés Portaluppi', '1980-09-16', 33, 'MED', NULL),
  ('Super Senior Fútbol', 'Felipe', 'Topo', 'Valdés Tocornal', '1980-08-18', 37, 'DEF', NULL),
  ('Super Senior Futbolito', 'Rodrigo', 'Vare', 'Varela Anabalón', '1979-01-21', 24, 'MED', NULL),
  ('Junior Fútbol', 'Sebastián', NULL, 'Vega Hidalgo', '2003-03-20', 1, NULL, NULL),
  ('Senior Fútbol', 'Gonzalo', 'Vasco', 'Velasco Navarro', '1980-05-24', 3, 'DEF', NULL),
  ('Super Senior Fútbol', 'Bernardo', 'Beri', 'Vergara Versluys', '1987-09-21', 11, 'DEL', NULL),
  ('Senior Fútbol', 'Francisco', NULL, 'Vial Plaza', '1992-03-10', 9, NULL, NULL),
  ('Senior Fútbol', 'Santiago', NULL, 'Vial Valdés', '1991-05-20', 12, NULL, NULL),
  ('Junior Fútbol', 'Miguel', NULL, 'Vial Vergara', '2001-11-30', 5, NULL, NULL),
  ('Super Senior Futbolito', 'Ezequiel', 'Exi', 'Vidal -', '1979-10-06', 31, 'MED', NULL);

UPDATE jugadores SET posicion = 'MED' WHERE posicion IN ('VOL','NED');
UPDATE jugadores SET posicion_2 = 'MED' WHERE posicion_2 IN ('VOL','NED');
UPDATE jugadores SET posicion_2 = NULL WHERE posicion_2 = posicion;

COMMIT;
